/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: cosi.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "cosi.pb-c.h"
void   announcement__init
                     (Announcement         *message)
{
  static Announcement init_value = ANNOUNCEMENT__INIT;
  *message = init_value;
}
size_t announcement__get_packed_size
                     (const Announcement *message)
{
  assert(message->base.descriptor == &announcement__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t announcement__pack
                     (const Announcement *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &announcement__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t announcement__pack_to_buffer
                     (const Announcement *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &announcement__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Announcement *
       announcement__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Announcement *)
     protobuf_c_message_unpack (&announcement__descriptor,
                                allocator, len, data);
}
void   announcement__free_unpacked
                     (Announcement *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &announcement__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   challenge__init
                     (Challenge         *message)
{
  static Challenge init_value = CHALLENGE__INIT;
  *message = init_value;
}
size_t challenge__get_packed_size
                     (const Challenge *message)
{
  assert(message->base.descriptor == &challenge__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t challenge__pack
                     (const Challenge *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &challenge__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t challenge__pack_to_buffer
                     (const Challenge *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &challenge__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Challenge *
       challenge__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Challenge *)
     protobuf_c_message_unpack (&challenge__descriptor,
                                allocator, len, data);
}
void   challenge__free_unpacked
                     (Challenge *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &challenge__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   commitment__init
                     (Commitment         *message)
{
  static Commitment init_value = COMMITMENT__INIT;
  *message = init_value;
}
size_t commitment__get_packed_size
                     (const Commitment *message)
{
  assert(message->base.descriptor == &commitment__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t commitment__pack
                     (const Commitment *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &commitment__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t commitment__pack_to_buffer
                     (const Commitment *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &commitment__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Commitment *
       commitment__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Commitment *)
     protobuf_c_message_unpack (&commitment__descriptor,
                                allocator, len, data);
}
void   commitment__free_unpacked
                     (Commitment *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &commitment__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   overlay_message__init
                     (OverlayMessage         *message)
{
  static OverlayMessage init_value = OVERLAY_MESSAGE__INIT;
  *message = init_value;
}
size_t overlay_message__get_packed_size
                     (const OverlayMessage *message)
{
  assert(message->base.descriptor == &overlay_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t overlay_message__pack
                     (const OverlayMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &overlay_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t overlay_message__pack_to_buffer
                     (const OverlayMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &overlay_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OverlayMessage *
       overlay_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OverlayMessage *)
     protobuf_c_message_unpack (&overlay_message__descriptor,
                                allocator, len, data);
}
void   overlay_message__free_unpacked
                     (OverlayMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &overlay_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protocol_packet__init
                     (ProtocolPacket         *message)
{
  static ProtocolPacket init_value = PROTOCOL_PACKET__INIT;
  *message = init_value;
}
size_t protocol_packet__get_packed_size
                     (const ProtocolPacket *message)
{
  assert(message->base.descriptor == &protocol_packet__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol_packet__pack
                     (const ProtocolPacket *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol_packet__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol_packet__pack_to_buffer
                     (const ProtocolPacket *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol_packet__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtocolPacket *
       protocol_packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtocolPacket *)
     protobuf_c_message_unpack (&protocol_packet__descriptor,
                                allocator, len, data);
}
void   protocol_packet__free_unpacked
                     (ProtocolPacket *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &protocol_packet__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   request_roster__init
                     (RequestRoster         *message)
{
  static RequestRoster init_value = REQUEST_ROSTER__INIT;
  *message = init_value;
}
size_t request_roster__get_packed_size
                     (const RequestRoster *message)
{
  assert(message->base.descriptor == &request_roster__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t request_roster__pack
                     (const RequestRoster *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &request_roster__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t request_roster__pack_to_buffer
                     (const RequestRoster *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &request_roster__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RequestRoster *
       request_roster__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RequestRoster *)
     protobuf_c_message_unpack (&request_roster__descriptor,
                                allocator, len, data);
}
void   request_roster__free_unpacked
                     (RequestRoster *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &request_roster__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   request_tree__init
                     (RequestTree         *message)
{
  static RequestTree init_value = REQUEST_TREE__INIT;
  *message = init_value;
}
size_t request_tree__get_packed_size
                     (const RequestTree *message)
{
  assert(message->base.descriptor == &request_tree__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t request_tree__pack
                     (const RequestTree *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &request_tree__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t request_tree__pack_to_buffer
                     (const RequestTree *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &request_tree__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RequestTree *
       request_tree__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RequestTree *)
     protobuf_c_message_unpack (&request_tree__descriptor,
                                allocator, len, data);
}
void   request_tree__free_unpacked
                     (RequestTree *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &request_tree__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response__init
                     (Response         *message)
{
  static Response init_value = RESPONSE__INIT;
  *message = init_value;
}
size_t response__get_packed_size
                     (const Response *message)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response__pack
                     (const Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response__pack_to_buffer
                     (const Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Response *
       response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Response *)
     protobuf_c_message_unpack (&response__descriptor,
                                allocator, len, data);
}
void   response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   roster__init
                     (Roster         *message)
{
  static Roster init_value = ROSTER__INIT;
  *message = init_value;
}
size_t roster__get_packed_size
                     (const Roster *message)
{
  assert(message->base.descriptor == &roster__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t roster__pack
                     (const Roster *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &roster__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t roster__pack_to_buffer
                     (const Roster *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &roster__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Roster *
       roster__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Roster *)
     protobuf_c_message_unpack (&roster__descriptor,
                                allocator, len, data);
}
void   roster__free_unpacked
                     (Roster *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &roster__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   server_identity__init
                     (ServerIdentity         *message)
{
  static ServerIdentity init_value = SERVER_IDENTITY__INIT;
  *message = init_value;
}
size_t server_identity__get_packed_size
                     (const ServerIdentity *message)
{
  assert(message->base.descriptor == &server_identity__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t server_identity__pack
                     (const ServerIdentity *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &server_identity__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t server_identity__pack_to_buffer
                     (const ServerIdentity *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &server_identity__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ServerIdentity *
       server_identity__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ServerIdentity *)
     protobuf_c_message_unpack (&server_identity__descriptor,
                                allocator, len, data);
}
void   server_identity__free_unpacked
                     (ServerIdentity *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &server_identity__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   token__init
                     (Token         *message)
{
  static Token init_value = TOKEN__INIT;
  *message = init_value;
}
size_t token__get_packed_size
                     (const Token *message)
{
  assert(message->base.descriptor == &token__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t token__pack
                     (const Token *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &token__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t token__pack_to_buffer
                     (const Token *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &token__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Token *
       token__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Token *)
     protobuf_c_message_unpack (&token__descriptor,
                                allocator, len, data);
}
void   token__free_unpacked
                     (Token *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &token__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tree_marshal__init
                     (TreeMarshal         *message)
{
  static TreeMarshal init_value = TREE_MARSHAL__INIT;
  *message = init_value;
}
size_t tree_marshal__get_packed_size
                     (const TreeMarshal *message)
{
  assert(message->base.descriptor == &tree_marshal__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tree_marshal__pack
                     (const TreeMarshal *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tree_marshal__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tree_marshal__pack_to_buffer
                     (const TreeMarshal *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tree_marshal__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TreeMarshal *
       tree_marshal__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TreeMarshal *)
     protobuf_c_message_unpack (&tree_marshal__descriptor,
                                allocator, len, data);
}
void   tree_marshal__free_unpacked
                     (TreeMarshal *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tree_marshal__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tree_node_info__init
                     (TreeNodeInfo         *message)
{
  static TreeNodeInfo init_value = TREE_NODE_INFO__INIT;
  *message = init_value;
}
size_t tree_node_info__get_packed_size
                     (const TreeNodeInfo *message)
{
  assert(message->base.descriptor == &tree_node_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tree_node_info__pack
                     (const TreeNodeInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tree_node_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tree_node_info__pack_to_buffer
                     (const TreeNodeInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tree_node_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TreeNodeInfo *
       tree_node_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TreeNodeInfo *)
     protobuf_c_message_unpack (&tree_node_info__descriptor,
                                allocator, len, data);
}
void   tree_node_info__free_unpacked
                     (TreeNodeInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tree_node_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define announcement__field_descriptors NULL
#define announcement__field_indices_by_name NULL
#define announcement__number_ranges NULL
const ProtobufCMessageDescriptor announcement__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Announcement",
  "Announcement",
  "Announcement",
  "",
  sizeof(Announcement),
  0,
  announcement__field_descriptors,
  announcement__field_indices_by_name,
  0,  announcement__number_ranges,
  (ProtobufCMessageInit) announcement__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor challenge__field_descriptors[1] =
{
  {
    "chall",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Challenge, chall),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned challenge__field_indices_by_name[] = {
  0,   /* field[0] = chall */
};
static const ProtobufCIntRange challenge__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor challenge__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Challenge",
  "Challenge",
  "Challenge",
  "",
  sizeof(Challenge),
  1,
  challenge__field_descriptors,
  challenge__field_indices_by_name,
  1,  challenge__number_ranges,
  (ProtobufCMessageInit) challenge__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor commitment__field_descriptors[1] =
{
  {
    "comm",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Commitment, comm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned commitment__field_indices_by_name[] = {
  0,   /* field[0] = comm */
};
static const ProtobufCIntRange commitment__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor commitment__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Commitment",
  "Commitment",
  "Commitment",
  "",
  sizeof(Commitment),
  1,
  commitment__field_descriptors,
  commitment__field_indices_by_name,
  1,  commitment__number_ranges,
  (ProtobufCMessageInit) commitment__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor overlay_message__field_descriptors[5] =
{
  {
    "tree_node_info",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(OverlayMessage, tree_node_info),
    &tree_node_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request_tree",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(OverlayMessage, request_tree),
    &request_tree__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tree_marshal",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(OverlayMessage, tree_marshal),
    &tree_marshal__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request_roster",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(OverlayMessage, request_roster),
    &request_roster__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "roster",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(OverlayMessage, roster),
    &roster__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned overlay_message__field_indices_by_name[] = {
  3,   /* field[3] = request_roster */
  1,   /* field[1] = request_tree */
  4,   /* field[4] = roster */
  2,   /* field[2] = tree_marshal */
  0,   /* field[0] = tree_node_info */
};
static const ProtobufCIntRange overlay_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor overlay_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OverlayMessage",
  "OverlayMessage",
  "OverlayMessage",
  "",
  sizeof(OverlayMessage),
  5,
  overlay_message__field_descriptors,
  overlay_message__field_indices_by_name,
  1,  overlay_message__number_ranges,
  (ProtobufCMessageInit) overlay_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protocol_packet__field_descriptors[6] =
{
  {
    "phase",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ProtocolPacket, phase),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "info",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtocolPacket, info),
    &overlay_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ann",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtocolPacket, ann),
    &announcement__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "comm",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtocolPacket, comm),
    &commitment__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chal",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtocolPacket, chal),
    &challenge__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtocolPacket, resp),
    &response__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol_packet__field_indices_by_name[] = {
  2,   /* field[2] = ann */
  4,   /* field[4] = chal */
  3,   /* field[3] = comm */
  1,   /* field[1] = info */
  0,   /* field[0] = phase */
  5,   /* field[5] = resp */
};
static const ProtobufCIntRange protocol_packet__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor protocol_packet__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ProtocolPacket",
  "ProtocolPacket",
  "ProtocolPacket",
  "",
  sizeof(ProtocolPacket),
  6,
  protocol_packet__field_descriptors,
  protocol_packet__field_indices_by_name,
  1,  protocol_packet__number_ranges,
  (ProtobufCMessageInit) protocol_packet__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor request_roster__field_descriptors[1] =
{
  {
    "roster_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RequestRoster, roster_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request_roster__field_indices_by_name[] = {
  0,   /* field[0] = roster_id */
};
static const ProtobufCIntRange request_roster__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor request_roster__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RequestRoster",
  "RequestRoster",
  "RequestRoster",
  "",
  sizeof(RequestRoster),
  1,
  request_roster__field_descriptors,
  request_roster__field_indices_by_name,
  1,  request_roster__number_ranges,
  (ProtobufCMessageInit) request_roster__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor request_tree__field_descriptors[1] =
{
  {
    "tree_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RequestTree, tree_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request_tree__field_indices_by_name[] = {
  0,   /* field[0] = tree_id */
};
static const ProtobufCIntRange request_tree__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor request_tree__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RequestTree",
  "RequestTree",
  "RequestTree",
  "",
  sizeof(RequestTree),
  1,
  request_tree__field_descriptors,
  request_tree__field_indices_by_name,
  1,  request_tree__number_ranges,
  (ProtobufCMessageInit) request_tree__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__field_descriptors[1] =
{
  {
    "resp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Response, resp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__field_indices_by_name[] = {
  0,   /* field[0] = resp */
};
static const ProtobufCIntRange response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response",
  "Response",
  "Response",
  "",
  sizeof(Response),
  1,
  response__field_descriptors,
  response__field_indices_by_name,
  1,  response__number_ranges,
  (ProtobufCMessageInit) response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor roster__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Roster, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "list",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Roster, n_list),
    offsetof(Roster, list),
    &server_identity__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aggregate",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Roster, aggregate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned roster__field_indices_by_name[] = {
  2,   /* field[2] = aggregate */
  0,   /* field[0] = id */
  1,   /* field[1] = list */
};
static const ProtobufCIntRange roster__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor roster__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Roster",
  "Roster",
  "Roster",
  "",
  sizeof(Roster),
  3,
  roster__field_descriptors,
  roster__field_indices_by_name,
  1,  roster__number_ranges,
  (ProtobufCMessageInit) roster__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor server_identity__field_descriptors[3] =
{
  {
    "public",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ServerIdentity, public_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ServerIdentity, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ServerIdentity, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned server_identity__field_indices_by_name[] = {
  2,   /* field[2] = address */
  1,   /* field[1] = id */
  0,   /* field[0] = public */
};
static const ProtobufCIntRange server_identity__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor server_identity__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ServerIdentity",
  "ServerIdentity",
  "ServerIdentity",
  "",
  sizeof(ServerIdentity),
  3,
  server_identity__field_descriptors,
  server_identity__field_indices_by_name,
  1,  server_identity__number_ranges,
  (ProtobufCMessageInit) server_identity__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor token__field_descriptors[6] =
{
  {
    "roster_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Token, roster_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tree_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Token, tree_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proto_id",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Token, proto_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "service_id",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Token, service_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "round_id",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Token, round_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tree_node_id",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Token, tree_node_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned token__field_indices_by_name[] = {
  2,   /* field[2] = proto_id */
  0,   /* field[0] = roster_id */
  4,   /* field[4] = round_id */
  3,   /* field[3] = service_id */
  1,   /* field[1] = tree_id */
  5,   /* field[5] = tree_node_id */
};
static const ProtobufCIntRange token__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor token__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Token",
  "Token",
  "Token",
  "",
  sizeof(Token),
  6,
  token__field_descriptors,
  token__field_indices_by_name,
  1,  token__number_ranges,
  (ProtobufCMessageInit) token__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tree_marshal__field_descriptors[5] =
{
  {
    "tree_node_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(TreeMarshal, tree_node_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tree_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(TreeMarshal, tree_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server_identity_id",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(TreeMarshal, server_identity_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "roster_id",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(TreeMarshal, roster_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "children",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TreeMarshal, n_children),
    offsetof(TreeMarshal, children),
    &tree_marshal__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tree_marshal__field_indices_by_name[] = {
  4,   /* field[4] = children */
  3,   /* field[3] = roster_id */
  2,   /* field[2] = server_identity_id */
  1,   /* field[1] = tree_id */
  0,   /* field[0] = tree_node_id */
};
static const ProtobufCIntRange tree_marshal__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor tree_marshal__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TreeMarshal",
  "TreeMarshal",
  "TreeMarshal",
  "",
  sizeof(TreeMarshal),
  5,
  tree_marshal__field_descriptors,
  tree_marshal__field_indices_by_name,
  1,  tree_marshal__number_ranges,
  (ProtobufCMessageInit) tree_marshal__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tree_node_info__field_descriptors[2] =
{
  {
    "to",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TreeNodeInfo, to),
    &token__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "from",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TreeNodeInfo, from),
    &token__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tree_node_info__field_indices_by_name[] = {
  1,   /* field[1] = from */
  0,   /* field[0] = to */
};
static const ProtobufCIntRange tree_node_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tree_node_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TreeNodeInfo",
  "TreeNodeInfo",
  "TreeNodeInfo",
  "",
  sizeof(TreeNodeInfo),
  2,
  tree_node_info__field_descriptors,
  tree_node_info__field_indices_by_name,
  1,  tree_node_info__number_ranges,
  (ProtobufCMessageInit) tree_node_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
